[package]
name = "tch"
version = "0.0.1"
authors = ["laurent <lmazare@gmail.com>"]
edition = "2018"

description = "PyTorch wrappers for rust"
repository = "https://github.com/LaurentMazare/tch-rs"
keywords = ["pytorch", "deep-learning", "machine-learning"]
categories = ["science"]
license = "Apache-2.0"

[dependencies]
libc = "0.2.0"

[build-dependencies]
cmake = "0.1"
