[package]
name = "tch"
version = "0.0.3"
authors = ["laurent <lmazare@gmail.com>"]
edition = "2018"

description = "Rust wrappers for the PyTorch C++ api (libtorch)."
repository = "https://github.com/LaurentMazare/tch-rs"
keywords = ["pytorch", "deep-learning", "machine-learning"]
categories = ["science"]
license = "Apache-2.0"

[dependencies]
libc = "0.2.0"
rand = "0.6.5"

[build-dependencies]
cc = "1.0"
cmake = "0.1"
